ldap_uri: 'ldaps://ldap.local.com:636'
ldap_base: 'dc=local,dc=com'
sudoer_base: 'ou=SUDOers,dc=local,dc=com'
tls_ca: '/etc/openldap/cacerts/cacert.pem'
tls_cert: '/etc/openldap/cacerts/client.cert'
tls_key:  '/etc/openldap/cacerts/client.key'
